name: DORA Compliance Audit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1' # Weekly audit

jobs:
  audit:
    name: DORA Audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # For uploading SARIF/reports if we add that later

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PanDoraSpec Audit
        uses: ./ # uses: pandoraspec/pandoraspec@v1 in real life
        with:
          target: 'https://petstore.swagger.io/v2/swagger.json' # Replace with your API
          vendor: 'MyCompany'
          format: 'pdf'
          output: 'dora_report.pdf'

      - name: Upload PDF Report
        if: always() # Upload report even if audit fails
        uses: actions/upload-artifact@v4
        with:
          name: dora-report
          path: dora_report.pdf
